apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  labels:
    app: shoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: shoppingacr.azurecr.io/shoppingclient:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingclient-configmap
                  key: ShoppingAPIUrl
      imagePullSecrets:
        - name: acr-secret
